In [3]:
import pandas as pd
import sqlite3
import numpy as np

In [10]:
conn = sqlite3.connect(r'C:\Users\Owner\dev\algobetting\infra\data\db\algobetting.db')
df = pd.read_sql_query("SELECT * FROM fbref_match_summary", conn)

df

,team,is_home,match_date,division,season,match_url,shots,shots_on_target,xg,npxg,...,opp_shots_on_target,opp_xg,opp_npxg,opp_cards_red,opp_psxg,opp_touches,opp_touches_att_pen_area,opp_touches_att_3rd,opp_pens_won,opp_corner_kicks
0,Leicester City,1,2025-04-07,Premier League,2024-2025,https://fbref.com/en/matches/d8efb6cc/Leiceste...,7.0,2.0,0.5,0.5,...,5.0,3.3,3.3,0,2.9,556.0,22.0,110.0,0,2
1,Newcastle Utd,0,2025-04-07,Premier League,2024-2025,https://fbref.com/en/matches/d8efb6cc/Leiceste...,16.0,5.0,3.3,3.3,...,2.0,0.5,0.5,0,0.4,680.0,16.0,150.0,0,12
2,Manchester Utd,1,2025-04-06,Premier League,2024-2025,https://fbref.com/en/matches/53e359bb/Manchest...,13.0,2.0,0.9,0.9,...,5.0,0.5,0.5,0,0.3,706.0,14.0,166.0,0,3
3,Manchester City,0,2025-04-06,Premier League,2024-2025,https://fbref.com/en/matches/53e359bb/Manchest...,9.0,5.0,0.5,0.5,...,2.0,0.9,0.9,0,0.2,541.0,26.0,126.0,0,5
4,Tottenham,1,2025-04-06,Premier League,2024-2025,https://fbref.com/en/matches/f671e515/Tottenha...,12.0,7.0,2.1,1.3,...,4.0,1.0,1.0,0,0.4,608.0,23.0,159.0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
623,Southampton,0,2024-08-17,Premier League,2024-2025,https://fbref.com/en/matches/34557647/Newcastl...,19.0,3.0,1.8,1.8,...,1.0,0.3,0.3,1,0.6,317.0,12.0,72.0,0,3
624,Ipswich Town,1,2024-08-17,Premier League,2024-2025,https://fbref.com/en/matches/a1d0d529/Ipswich-...,7.0,2.0,0.5,0.5,...,5.0,2.6,2.6,0,2.3,720.0,46.0,200.0,0,10
625,Liverpool,0,2024-08-17,Premier League,2024-2025,https://fbref.com/en/matches/a1d0d529/Ipswich-...,18.0,5.0,2.6,2.6,...,2.0,0.5,0.5,0,0.2,497.0,16.0,98.0,0,2
626,Manchester Utd,1,2024-08-16,Premier League,2024-2025,https://fbref.com/en/matches/cc5b4244/Manchest...,14.0,5.0,2.4,2.4,...,2.0,0.4,0.4,0,0.9,540.0,21.0,117.0,0,8
627,Fulham,0,2024-08-16,Premier League,2024-2025,https://fbref.com/en/matches/cc5b4244/Manchest...,10.0,2.0,0.4,0.4,...,5.0,2.4,2.4,0,2.1,640.0,22.0,183.0,0,7

In [12]:
def apply_weighted_avg(col, match_date, match_red, decay_rate=0.005, time_window=365):
    # Create a mask for non-NaN values
    valid_mask = ~pd.isna(col)
    
    # If all values are NaN, return NaN
    if not valid_mask.any():
        return np.nan
    
    # Filter out NaN values
    valid_col = col[valid_mask].copy()  # Create a copy to avoid modifying original
    valid_dates = match_date[valid_mask]
    valid_red = match_red[valid_mask]
    
    # Get most recent date
    recent_date = max(valid_dates)
    
    # Create a time window mask (only include matches within time_window days)
    time_window_mask = (recent_date - valid_dates).dt.days <= time_window
    
    # If no matches in the time window, return NaN
    if not time_window_mask.any():
        return np.nan
    
    # Apply time window filter
    valid_col = valid_col[time_window_mask]
    valid_dates = valid_dates[time_window_mask]
    valid_red = valid_red[time_window_mask]
    
    # Calculate weights for matches within the time window
    match_weight = np.exp(-(recent_date - valid_dates).dt.days * decay_rate)
    
    # Reduce weight for matches with red cards (now using 0.3 instead of 0.5)
    match_weight = np.where(valid_red == 1, match_weight * 0.3, match_weight)
    
    # Calculate weighted average
    weighted_avg = sum(match_weight * valid_col) / sum(match_weight) 

    return weighted_avg

df = df.drop_duplicates(subset=['match_url', 'team'])

df['match_date'] = pd.to_datetime(df['match_date'])
df['match_red'] = df["cards_red"].astype(int) + df["opp_cards_red"].astype(int)

# Define metrics to use
attack_metrics = ['shots', 'shots_on_target', 'xg', 'npxg', 'touches_att_pen_area', 'touches_att_3rd']
defense_metrics = ['opp_shots', 'opp_shots_on_target', 'opp_xg', 'opp_npxg', 'opp_touches_att_pen_area', 'opp_touches_att_3rd']

# Create a unique match identifier
df['match_id'] = df['match_url']  

# Process each team
team_metrics = []

for team_name in df['team'].unique():
    # Get all matches for this team
    team_matches = df[df['team'] == team_name].sort_values('match_date')
    
    # For each match, calculate weighted averages of previous matches
    for i, (idx, current_match) in enumerate(team_matches.iterrows()):
        if i > 0:  # Skip first match
            prev_matches = team_matches.iloc[:i]
            
            # Calculate all metrics in one go
            metrics_dict = {}
            
            # Attack metrics
            for metric in attack_metrics:
                weighted_avg = apply_weighted_avg(
                    prev_matches[metric],
                    prev_matches['match_date'],
                    prev_matches['match_red']
                )
                metrics_dict[f'weighted_attack_{metric}'] = weighted_avg
            
            # Defense metrics
            for metric in defense_metrics:
                weighted_avg = apply_weighted_avg(
                    prev_matches[metric],
                    prev_matches['match_date'],
                    prev_matches['match_red']
                )
                metrics_dict[f'weighted_defense_{metric}'] = weighted_avg
            
            # Add match info
            metrics_dict['team'] = team_name
            metrics_dict['match_id'] = current_match['match_id']
            metrics_dict['opp_team'] = current_match['opp_team']
            
            team_metrics.append(metrics_dict)

# Convert to dataframe
metrics_df = pd.DataFrame(team_metrics)

# When merging, keep all team-match combinations from the original data
final_df = df.merge(
    metrics_df,
    on=['team', 'match_id', 'opp_team'],
    how='left'
)

# Create opponent metrics dataframe
opp_metrics_df = metrics_df.rename(columns={
    'team': 'opp_team',
    'opp_team': 'team'
})
opp_metrics_df.columns = [f'{col}_opp' if col.startswith('weighted') else col for col in opp_metrics_df.columns]

# Merge opponent metrics
final_df = final_df.merge(
    opp_metrics_df,
    on=['team', 'match_id', 'opp_team'],
    how='left'
)

final_df

,team,is_home,match_date,division,season,match_url,shots,shots_on_target,xg,npxg,...,weighted_attack_xg_opp,weighted_attack_npxg_opp,weighted_attack_touches_att_pen_area_opp,weighted_attack_touches_att_3rd_opp,weighted_defense_opp_shots_opp,weighted_defense_opp_shots_on_target_opp,weighted_defense_opp_xg_opp,weighted_defense_opp_npxg_opp,weighted_defense_opp_touches_att_pen_area_opp,weighted_defense_opp_touches_att_3rd_opp
0,Leicester City,1,2025-04-07,Premier League,2024-2025,https://fbref.com/en/matches/d8efb6cc/Leiceste...,7.0,2.0,0.5,0.5,...,1.641469,1.525481,27.394965,154.623003,12.765053,4.325572,1.312010,1.262558,24.266470,154.910355
1,Newcastle Utd,0,2025-04-07,Premier League,2024-2025,https://fbref.com/en/matches/d8efb6cc/Leiceste...,16.0,5.0,3.3,3.3,...,0.750664,0.720087,15.710686,106.963629,16.130546,5.494694,1.887059,1.825313,31.816265,195.700380
2,Manchester Utd,1,2025-04-06,Premier League,2024-2025,https://fbref.com/en/matches/53e359bb/Manchest...,13.0,2.0,0.9,0.9,...,1.781890,1.685822,34.213599,244.588766,9.717322,3.708855,1.319316,1.248066,18.973256,103.936086
3,Manchester City,0,2025-04-06,Premier League,2024-2025,https://fbref.com/en/matches/53e359bb/Manchest...,9.0,5.0,0.5,0.5,...,1.353017,1.266695,25.390819,151.952874,11.391665,3.949791,1.501332,1.414472,21.819881,148.418899
4,Tottenham,1,2025-04-06,Premier League,2024-2025,https://fbref.com/en/matches/f671e515/Tottenha...,12.0,7.0,2.1,1.3,...,0.836449,0.799419,17.576982,126.777179,17.076964,6.432989,2.281046,2.105396,32.140872,176.702024
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
613,Southampton,0,2024-08-17,Premier League,2024-2025,https://fbref.com/en/matches/34557647/Newcastl...,19.0,3.0,1.8,1.8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
614,Ipswich Town,1,2024-08-17,Premier League,2024-2025,https://fbref.com/en/matches/a1d0d529/Ipswich-...,7.0,2.0,0.5,0.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
615,Liverpool,0,2024-08-17,Premier League,2024-2025,https://fbref.com/en/matches/a1d0d529/Ipswich-...,18.0,5.0,2.6,2.6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
616,Manchester Utd,1,2024-08-16,Premier League,2024-2025,https://fbref.com/en/matches/cc5b4244/Manchest...,14.0,5.0,2.4,2.4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
617,Fulham,0,2024-08-16,Premier League,2024-2025,https://fbref.com/en/matches/cc5b4244/Manchest...,10.0,2.0,0.4,0.4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN